version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.12.2-stretch-node
  environment:
    DOCKER_IMAGE: conductor
    DOCKER_REGISTRY: hub.docker.com
    DOCKER_NAMESPACE: nextdoor

jobs:
  build:
    docker:
      - image: circleci/golang:1.12.2-stretch-node
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/Nextdoor/conductor
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: make -C conductor docker-login docker-populate-cache
      - run:
          name: Set environment variables
          command: |
            # Set vars.
            SHA1=$(echo $CIRCLE_SHA1 | cut -c -16)
            DOCKER_TAG=$(echo ${CIRCLE_TAG:-$CIRCLE_BRANCH-$SHA1} | sed 's|/|_|g')
            CACHE_FROM="${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${DOCKER_IMAGE}"
            # Export them into bash env.
            echo "export SHA1=$SHA1" >> $BASH_ENV
            echo "export DOCKER_TAG=$DOCKER_TAG" >> $BASH_ENV
            echo "export CACHE_FROM=$CACHE_FROM" >> $BASH_ENV
      - run:
          name: Install goimports
          command: |
            go get golang.org/x/tools/cmd/goimports
            go install golang.org/x/tools/cmd/goimports
      # Install yarn
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: docker pull $CACHE_FROM || true
      - run: make postgres
      # Compile the frontend
      - run: make -C conductor/frontend prod-compile
      - run: make docker-build
      - run: make test

workflows:
  version: 2
  workflow:
    jobs:
      - build
