version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12.2-stretch-node
    steps:
      - checkout
      - run: echo "Hello World"
      - run: make postgres
      - run: make build
      - run: make test

workflows:
  version: 2
  workflow:
    jobs:
      - build
